### PR TITLE
Fixed charts container width

### PR DESCRIPTION
**Pull request by sakhawy**
Related issue #44

### CODE REVIEW

**Comment by Darkbeast-glitch** [comment]
Cool @sakhawy , buh i see that you expanded the col to 12 -   let me explain something to you 
image

the charts are three, and each  of them has a span of 4 , the one you changed was for the first chart, so meaning the charts will look like this
image

 so yes, it's supposed to be 4  for each of the  charts and not 12 

kindly check if i am wrong before it's being merged

**Comment by sakhawy** [comment]
Hi @Darkbeast-glitch! Thanks for taking a look! I checked again and it looks like the rest of the page -including the other charts and page content after the first chart- is mistakingly nested inside that first column(?) That's why the lazy fix of changing the class from `col-md-4` to `col-md-12` worked I think.
image
(The yellow underline is highlighted by a popular VSCode extension called "Highlight Matching Tags".)

I did a quick count of opened `div` tags vs closed ones and looks like there are 2 missing closing `</div>`s:
```bash
$ grep -o "<div" schedule_talx.html | wc -l
13
$ grep -o "</div" schedule_talx.html | wc -l
11
```

**Comment by Darkbeast-glitch** [comment]
Thank you soo much @sakhawy  for the help 
kindly check the website again for the chart

**Comment by sakhawy** [comment]
Oh! The chart got removed I see. The other ones look good! Thanks, I'm closing this PR! Should I close the other issue as well since that chart isn't there anymore (#46)?

**Comment by Darkbeast-glitch** [comment]
> Oh! The chart got removed I see. The other ones look good! Thanks, I'm closing this PR! Should I close the other issue as well since that chart isn't there anymore (#46)?

yes sir, thank you very much for your help sir

**Pull request closed without merging**
